
# Install latest verison of Docker
- name: Docker Install
  package:
    name: docker
    state: latest

# Reload
- name: Daemon Reload / Docker Start / Enable
  systemd:
    name: docker
    enabled: yes
    state: restarted
    daemon_reload: yes