# Get Jenkins Repo Key
- name: Get the Repo Key
  rpm_key:
    key: "{{ jenkins_key_url }}"
    state: present

# Add the repo
- name: Get and add package
  get_url:
    url: "{{ jenkins_repo_url }}"
    dest: "{{ yum_repo_folder }}/jenkins.repo"
    mode: 0664

# Java and Jenkins Installation
- name: Install java and jenkins
  package:
    name: "{{ item }}"
    state: latest
  with_items:
  - "java-1.8.0-openjdk"
  - "jenkins"

# Enable and start jenkins
- name: Enable and start Jenkins
  systemd:
    name: jenkins
    state: started
    daemon_reload: yes
    enabled: yes
